services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - ROBOT_IP=${ROBOT_IP}
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt_broker/mosquitto/config:/mosquitto/config
      - ./mqtt_broker/mosquitto/data:/mosquitto/data
      - ./mqtt_broker/mosquitto/log:/mosquitto/log
    

  mqtt_websocket:
    image: matteozucchellieth/mqtt_websocket
    build: ./mqtt_websocket
    container_name: mqtt_websocket
    depends_on:
      - mosquitto
    ports:
      - "12345:12345"
    restart: unless-stopped
    environment:
      - RASPBERRY_PI_IP=${RASPBERRY_PI_IP}
    
# FOR THE NAUTICA APP, SET THE ROBOT AND THE RASPBERRY PI MANUALLY IN THE PAGES for now
  nautica_app:
    image: matteozucchellieth/nautica_app
    build: ./nautica_app
    container_name: nautica_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    

  db_api_raspi:
    build: ./db_api_raspi
    image: matteozucchellieth/raspberry_db_api:latest
    container_name: raspberry_db_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./db_api_raspi:/app
    working_dir: /app
    environment:
      - API_PORT=8000
      - ROBOT_DB=/app/robot.db
      - REMOTE_SYNC_ENDPOINT=http://${ROBOT_IP}:8001/sync
    

  sync_worker:
    build: ./db_api_raspi
    image: matteozucchellieth/raspberry_db_sync:latest
    container_name: raspberry_db_sync
    restart: unless-stopped
    volumes:
      - ./db_api_raspi:/app
    working_dir: /app
    environment:
      - REMOTE_SYNC_ENDPOINT=http://${ROBOT_IP}:8001/sync
    depends_on:
      - db_api_raspi
    command: ["sh", "-c", "python -u -m app.sync $$REMOTE_SYNC_ENDPOINT"]